### ISSUE TITLE
Thick composition underline in the Keyword Matcher has a duller tone than selected

### ISSUE THREAD

**Issue by SonicRay100** [blu3mania/npp-papyrus#49] opened 2023-06-21 13:03 UTC
Under keyword matcher, selecting "Thick composition underline" turns the colour selected dull in the latest version of the plugin (v1.0.0 (Build 31) ) using the latest version of Notepad++ (v8.5.4 64-bit).

What I have tested:

- Both "Matched Style" and "Unmatched Style" have a dull tone when selecting "Thick composition underline".
- It doesn't change when switching between light mode and dark mode in Notepad++ .
- Resetting the lexar styles under advanced for this plugin doesn't fix the issue.
- The colour is not dull using an older version of plugin (Papyrus Plugin = v0.3.0 (Build 24), Notepad++ v8.3.3 64-bit).

What happens in an older version of the plugin:

Papyrus Plugin = v0.3.0 (Build 24)
Notepad++ v8.3.3 64-bit

- "Thick composition underline" has the same tone as "Thin composition underline".

What happens in the newer version of the plugin

Papyrus Plugin = v1.0.0 (Build 31) 
Notepad++ v8.5.4 64-bit

- "Thick composition underline" has a duller tone compared to "Thin composition underline".

Image:

![Untitled](https://github.com/blu3mania/npp-papyrus/assets/69745689/2dfc4262-5a28-40fe-a33d-8ba9da6d7513)

**Comment by blu3mania** [comment] 2023-06-22 20:49
This is caused by Scintilla's change in 5.3.0 (see https://www.scintilla.org/ScintillaHistory.html) that applied outline alpha to INDIC_COMPOSITIONTHICK. I just pushed a commit to force the outline to always be opaque.

**Comment by blu3mania** [comment] 2023-06-22 21:40
Released v1.0.1 so I am closing this.

**Closed by blu3mania** 2023-06-22 21:40 UTC

**Comment by SonicRay100** [comment] 2023-06-23 07:18
Awesome. Thanks for the great work :).
